language: node_js
script: npm run build
deploy:
  provider: pages
  github-token: "$GITHUB_TOKEN"
  local-dir: build
  target-branch: gh-pages
  keep-history: tru
  skip-cleanup: true
  verbose: true
  on:
    branch: master
notifications:
  slack:
    secure: OPNTA6IyDxMj9Rqybe07+iluiCn+dy++4iCXN0cqqvBiIuKOqAhuMurjITzXCey9nBKHvQMZre1qHa6U+pEWFEV5OctMwDZrCJ+2StpZ1KzrCa/aieCeQ9S7Gy0KcER6A25s+7a9TA60ci/2ERfPOalpqRy3S/MSZANv+Lr7pFh0HlSyT7DEmTD6pNp7d5ssKBE78QGAU+ysss3WkYCeuMhLaKgAO4LzfO8Ctp5X6AwYU/8m+jSzyJR66U/ama1sKCagW86fM8+7OihkMw9XrG3G+ND4E5mdNVmV1hF4SdLPHE1gXA/ECEIiVO/EpO/IG7LGXdIiuoz6eZuX6MpYd9dLagMDcMpkBQmfDWT8md73LUQgNThER5Dfd4xVZTPPVXvHzSb0TptZ55R10Vwr/8rP8pw7eKW+MTX0Eyk5j8WGxHKEy8mX5DdohXMC9VcZpLMj3hI7dydDlB+goodu2K2M/hAyfuPvbZfxU/SjKBFOAOZdmQta+sDvUt9rdL6WPxFHgWrszGFDL8U9vHgYi+g2DR1M7OnwGv0Ku0CqIaiIAszkYUwixV4yljKt7NaVZTUvvhGSBrSFJS80ADcXg5kJc12SGub9CENdZwvA5A1SnvJu7UonVfcGgK3CtcYkHbpx/q6Pc6tNbGC0BvZt24byf6nZi7dy9FDe1t1FlAo=
